{"name": "test_count_of_all_products", "status": "skipped", "statusDetails": {"message": "XFAIL Wait for fix bug\n\nselenium.common.exceptions.TimeoutException: Message:", "trace": "browser = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"83e4f6a8a8e4583a5a957ed4dbdf343a\")>\n\n    @pytest.mark.xfail(reason=\"Wait for fix bug\")\n    def test_count_of_all_products(browser):\n        \"\"\"\n        Test case TC-3\n        \"\"\"\n        browser.get(URL)\n    \n        browser.execute_script(\"window.scrollTo(0, document.body.scrollHeight);\")\n    \n>       WebDriverWait(browser, timeout=10, poll_frequency=2).until(EC.text_to_be_present_in_element(\n            (By.CLASS_NAME, \"current-post\"), \"17\"))\n\ntests\\test_shop.py:62: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"83e4f6a8a8e4583a5a957ed4dbdf343a\")>\nmethod = <function text_to_be_present_in_element.<locals>._predicate at 0x0000023FA5F86200>\nmessage = ''\n\n    def until(self, method, message: str = \"\"):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message:\n\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py:95: TimeoutException"}, "description": "\n    Test case TC-3\n    ", "start": 1681748141031, "stop": 1681748152405, "uuid": "dd651e2c-ca22-43d4-bcf5-152e12181154", "historyId": "7f2f2c0789e4f8e5b3b27ede23903a70", "testCaseId": "fbaf36f5b8599b571268ed0e3d8725a7", "fullName": "tests.test_shop#test_count_of_all_products", "labels": [{"name": "tag", "value": "@pytest.mark.xfail(reason='Wait for fix bug')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_shop"}, {"name": "host", "value": "DESKTOP-1H76NUL"}, {"name": "thread", "value": "9288-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_shop"}]}